/*
 * This source file was generated by the Gradle 'init' task
 */
package br.edu.fatecpg.streamlambda;

import org.junit.jupiter.api.Test;

class AppTest {

    @Test
    void appHasAGreeting() {
        //
    }
}
